cverifier/cverifier/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('verifier/', include('verifier.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cverifier/verifier/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'verifier'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='verifier/login.html')),
    path('logout/', views.logout_view),
    path('', views.index, name='index'),
    path('dirform/', views.DirectoryCreateView.as_view(), name='dirform'),
    path('fileform/', views.FileCreateView.as_view(), name='fileform'),
    path('delete_dir/<int:pk>', views.DirectoryDelete.as_view(), name='delete_dir'),
    path('delete_file/<int:pk>', views.FileDelete.as_view(), name='delete_file'),
    path('code/<int:pk>', views.code, name='code'),
    path('frama/<int:pk>', views.frama_output, name='frama'),
]

cverifier/verifier/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.urls import reverse
from django.conf import settings

class UserManager(BaseUserManager):
    def create_user(self, login, password=None):
        user = self.model(login=login)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, password=None):
        user = self.create_user(login, password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    name = models.CharField(max_length=256)
    login = models.CharField(max_length=40, unique=True)
    USERNAME_FIELD = 'login'
    is_admin = models.BooleanField(default=False)
    objects = UserManager()
    
    def __str__(self):
        return self.login

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

class Directory(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    name = models.TextField(max_length=256)
    desc = models.TextField(blank=True)
    creation_date = models.DateTimeField()
    availability_flag = models.BooleanField()
    def get_my_path(self):
        return ('' if self.parent is None else Directory.objects.get(pk=self.parent.pk).get_my_path()) + self.name + '/'
    def get_absolute_url(self):
        return reverse('verifier:index')
    def __str__(self):
        return self.name


class WithSections(models.Model):
    pass


class FileSection(WithSections):
    parent = models.ForeignKey(WithSections, on_delete=models.CASCADE, related_name='file_parent')
    name = models.CharField(max_length=256, blank=True)
    desc = models.TextField(blank=True)
    creation_date = models.DateTimeField()


def upload_path(instance, filename):
    return Directory.objects.get(pk=instance.directory.pk).get_my_path() + filename


class File(WithSections):
    directory = models.ForeignKey(Directory, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField(max_length=256)
    file_cont = models.FileField('file', upload_to=upload_path)
    desc = models.TextField(blank=True)
    creation_date = models.DateTimeField('creation date')
    availability_flag = models.BooleanField()
    def get_absolute_url(self):
        return reverse('verifier:index')
    def __str__(self):
        return self.name


class SectionCategory(models.Model):
    class CategoryType(models.TextChoices):
        PROCEDURE = 'proc', _('Procedure')
        PROPERTY = 'prop', _('Property')
        LEMMA = 'lemma', _('Lemma')
        ASSERTION = 'assert', _('Assert')
        INVARIANT = 'inv', _('Invariant')
        VARIANT = 'var', _('Variant')
        PRECONITION = 'precond', _('Precondition')
        POSTCONDITION = 'postcond', _('Postcondition')

    file_section = models.OneToOneField(
        FileSection,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    category_type = models.CharField(
        max_length=8,
        choices=CategoryType.choices,
        default=CategoryType.INVARIANT,
    )


class SectionStatus(models.Model):
    class StatusType(models.TextChoices):
        PROVED = 'prov', _('Proved')
        INVALID = 'inv', _('Invalid')
        COUNTEREXAMPLE = 'counter', _('Counterexample')
        UNCHECKED = 'unch', _('Unchecked')

    file_section = models.OneToOneField(
        FileSection,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    category_type = models.CharField(
        max_length=8,
        choices=StatusType.choices,
        default=StatusType.UNCHECKED,
    )


class StatusData(models.Model):
    content = models.TextField()
    status = models.ForeignKey(SectionStatus, on_delete=models.CASCADE)

cverifier/verifier/forms.py
from bootstrap_modal_forms.forms import BSModalModelForm
from django.forms import ModelForm
from .models import Directory, File

class DirectoryForm(BSModalModelForm):
    class Meta:
        model = Directory
        fields = ['name', 'parent', 'desc']

    #def __init__(self, *args, **kwargs):
        #owner = kwargs.pop('owner')
        #super(DirectoryForm, self).__init__(*args, **kwargs)

class FileForm(BSModalModelForm):
    class Meta:
        model = File
        fields = ['name', 'directory', 'file_cont', 'desc']

    #def __init__(self, *args, **kwargs):
        #owner = kwargs.pop('owner')
        #super(FileForm, self).__init__(*args, **kwargs)

cverifier/verifier/views.py
import re
import os
import html
import subprocess as sub

from django.shortcuts import render, redirect
from django.views.generic import CreateView, DeleteView
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse
from bootstrap_modal_forms.generic import BSModalCreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth import logout

from .models import *
from .forms import DirectoryForm, FileForm

def logged_in_only(view):
    def inner(request, *args, **kwargs):
        if request.user.is_authenticated:
            return view(request, *args, **kwargs)
        return HttpResponseForbidden()
    return inner

def logout_view(request):
    logout(request)
    return redirect('/verifier')

@ensure_csrf_cookie
@login_required(login_url='login/')
def index(request):
    directories = Directory.objects.filter(parent=None)
    files = File.objects.all
    context = {
        'directories': directories,
        'files': files
    }
    return render(request, 'verifier/index.html', context)

class DirectoryCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'verifier/form.html'
    form_class = DirectoryForm
    success_message = 'Success: directory was created.'
    success_url = reverse_lazy('verifier:index')

    def form_valid(self, form):
        form.instance.creation_date = timezone.now()
        x = form.instance.availability_flag
        form.instance.availability_flag = True if x is None else x
        form.instance.owner = self.request.user
        return super().form_valid(form)

class FileCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'verifier/form.html'
    form_class = FileForm
    success_message = 'Success: file was created.'
    success_url = reverse_lazy('verifier:index')

    def form_valid(self, form):
        form.instance.creation_date = timezone.now()
        x = form.instance.availability_flag
        form.instance.availability_flag = True if x is None else x
        form.instance.owner = self.request.user
        return super().form_valid(form)

class DirectoryDelete(LoginRequiredMixin, DeleteView):
    model = Directory
    success_url = reverse_lazy('verifier:index')

class FileDelete(LoginRequiredMixin, DeleteView):
    model = File
    success_url = reverse_lazy('verifier:index')

@logged_in_only
def code(request, pk):
    data = {}
    if request.method == 'POST':
        file_obj = File.objects.get(pk=pk)
        if file_obj != None:
            try:
                with file_obj.file_cont.open('r') as f:
                    data['filecontent'] = f.read()
            except:
                pass
    return JsonResponse(data)

@logged_in_only
def frama_output(request, pk):
    data = {}
    if request.method == 'POST':
        file_path = File.objects.get(pk=pk).file_cont.path
        params = request.POST.getlist('params[]')
        data['result'], goals = parse(sub.run(['frama-c'] + params + [file_path], capture_output=True).stdout.decode().splitlines(True))
        for key in goals:
            fs = FileSection.objects.create(parent=File.objects.get(pk=pk), creation_date=timezone.now())
            SectionCategory.objects.create(file_section=fs, category_type=goals[key][1])
            ss = SectionStatus.objects.create(file_section=fs, category_type=goals[key][2])
            StatusData.objects.create(status=ss, content=goals[key][3])
    return JsonResponse(data)

def parse(lines):
    p = re.compile(r'^-{60}\n$')

    # 0 -> goal lines, 1 -> result lines
    int_lines = [[], []]

    mp = {
        'post-condition': 'postcond',
        'pre-condition': 'precond',
        'lemma': 'lemma',
        'assertion': 'assert',
        'property': 'prop',
        'variant': 'var'
    }

    res_mp = {
        'unknown': 'unch',
        'valid': 'prov',
        'failed': 'counter',
        'false': 'counter',
        'invalid': 'inv'
    }

    color_mp = {
        'unch': 'white',
        'prov': 'green',
        'counter': 'orange',
        'inv': 'red'
    }

    for i, pair in enumerate(zip(lines, lines[1:])):
        for _ in range(2):
            if p.match(pair[_]) and pair[1 - _] == '\n':
                int_lines[_].append(i + 2 - 3 * _)

    if len(int_lines[0]) is not len(int_lines[1]):
        print('Could not parse frama-c output.')
        return '', ''

    goals = {}
    for gl, res in zip(int_lines[0], int_lines[1]):
        # Assign (line number, goal name, result, section content) for each goal line number in goal lines.
        # Goal name relates to the section name.
        line = lines[gl].strip()
        words = line.split()
        res_words = lines[res].strip().split()
        result = res_words[res_words.index('returns') + 1].lower()
        # len('Goal ') == 5
        goal_str = line[5:line.find('(') - 1].lower()
        if 'invariant' in goal_str:
            goal_str = 'inv'
        else:
            for key in mp:
                if key in goal_str:
                    goal_str = mp[key]
                    break
        goals[gl] = (int(re.search(r'\d+', words[words.index('line') + 1]).group()), goal_str, res_mp.get(result, result), ''.join(lines[gl:res + 1]))

    to_print = '<pre>\n'
    s, e = 0, 0
    for i, line in enumerate(lines):
        to_print += html.escape(line)
        if int_lines[0] and i == int_lines[0][s]:
            to_print += '<button onclick="$(document).ready(() => {{$(\'#goal{}\').toggle();}});">Hide/Unhide</button>\n'.format(i)
            to_print += '<div id="goal{0}" style="background-color:{1};">\n'.format(i, color_mp[goals[i][2]])
            s += 1
            if s >= len(int_lines[0]):
                s = 0
        if int_lines[1] and i == int_lines[1][e]:
            to_print += '</div>\n'
            e += 1
            if e >= len(int_lines[1]):
                e = 0
    to_print += '</pre>\n'
    return to_print, goals

cverifier/verifier/templates/verifier/base.html
<!DOCTYPE html>
<html lang="en-us">

<head>
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script> -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script src="{% static 'verifier/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'verifier/script.js' %}" type="text/javascript"></script>
<script src="{% static 'verifier/codemirror-5.61.1/lib/codemirror.js' %}"></script>
<link rel="stylesheet" href="{% static 'verifier/codemirror-5.61.1/lib/codemirror.css' %}">
<script src="{% static 'verifier/codemirror-5.61.1/mode/clike/clike.js' %}"></script>

{% block style %}
{% endblock %}

<link rel="icon" href="{% static 'verifier/images/c_icon.png' %}" type="image/x-icon">

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="author" content="Mykhailo Shevchenko">
<meta name="keywords" content="C, programming, verifier, invariant, invariants, ACSL, Frama-C, validator, validate, verify, check, prove">
<meta name="description" content="An application for writing down and proving invariants for simple programs written in the C programming language">

<title>C programs verifier</title>
</head>
<body>

{% block content %}
{% endblock content %}

</body>

</html>

cverifier/verifier/templates/verifier/form.html
<form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}

 <div class="modal-header">
    <h5 class="modal-title">Add</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} invalid{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>

</form>

cverifier/verifier/templates/verifier/index.html
{% extends "verifier/base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'verifier/style.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid">

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<script>
$(document).ready(() => {

    csrftoken = Cookies.get('csrftoken');
    opened_file = '';

    $("#add-dir").modalForm({
        formURL: "{% url 'verifier:dirform' %}"
    });

    $("#add-file").modalForm({
        formURL: "{% url 'verifier:fileform' %}"
    });

    editor = CodeMirror.fromTextArea(document.getElementsByTagName('textarea')[0], {
        mode: "clike"
    });

});

function loadFile(n) {
    $(document).on('click', '#file' + n, (e) => {
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url 'verifier:code' 1234 %}'.replace(/1234/, n.toString()),
            data:
            {
                pk: n,
                csrfmiddlewaretoken: csrftoken
            },
            success: (data) => {
                // $('.ver-code textarea:first').html(data.filecontent);
                // console.log(typeof data.filecontent);
                // console.log(data.filecontent);
                editor.getDoc().setValue(data.filecontent);
                opened_file = n;
            }
        });
    });
}

function runFrama(parameters=['-wp', '-wp-print']) {
    $(document).on('click', '#run-btn', (e) => {
        if (opened_file) {
            e.preventDefault();
            $.ajax({
                type:'POST',
                url:'{% url 'verifier:frama' 1234 %}'.replace(/1234/, opened_file.toString()),
                data:
                {
                    pk: opened_file,
                    params: parameters,
                    csrfmiddlewaretoken: csrftoken
                },
                success: (data) => {
                    $('.ver-program-element:first').html(data.result);
                }
            });
        }
    });
}

function deleteDir(n) {
    $(document).on('submit', '#d' + n, (e) => {
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url 'verifier:delete_dir' 1234 %}'.replace(/1234/, n.toString()),
            data:
            {
                pk: n,
                csrfmiddlewaretoken: csrftoken
            },
            success: () => {
                $("#dir" + n).remove();
            }
        });
    });
}

function deleteFile(n) {
    $(document).on('submit', '#f' + n, (e) => {
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url 'verifier:delete_file' 1234 %}'.replace(/1234/, n.toString()),
            data:
            {
                pk: n,
                csrfmiddlewaretoken: csrftoken
            },
            success: () => {
                $("#li" + n).remove();
            }
        });
    });
}
</script>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <button ="dropdown-toggle" data-toggle="dropdown">
        Project
      </button>
      <div class="dropdown-menu">
        <button class="dropdown-item" id="add-dir">Add directory</button>
        <button class="dropdown-item" id="add-file">Add file</button>
      </div>
    </li>
    <li class="nav-item">
      <button id="run-btn">Run</button>
      <script>
        $(document).ready(() => {runFrama();});
      </script>
    </li>
    <li class="nav-item dropdown">
      <button class="dropdown-toggle" data-toggle="dropdown">Help</button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="https://frama-c.com">About Frama-C</a>
      </div>
    </li>
    <li class="nav-item">
        <button onclick="location.href='/verifier/logout'">Log out</button>
    </li>
  </ul>
</nav>

  <main>
    <div class="ver-project-tree">
    <ul>
    {% if directories %}
    {% for dir in directories %}
      {% include 'verifier/tree_dir_template.html' %}
    {% endfor %}
    {% endif %}
    </ul>
    </div>

    <div class="ver-code">
      <textarea spellcheck="false" autofocus>
      #include &quot;stdio.h&quot;
int main() {
    printf(&quot;Hello World!\n&quot;);
      </textarea>
    </div>

    <div class="ver-program-element"></div>

    <div class="ver-tabs">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#provers">Provers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#vcs">VCs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#result">Result</a>
        </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div id="provers" class="container tab-pane active"><br>
            <form action="" method="post" id="prover-form">{% csrf_token %}
              <p>Please select the prover:</p>
              <input type="radio" id="alt-ergo" name="prover" value="alt-ergo">
              <label for="alt-ergo">Alt-Ergo</label><br>
              <input type="radio" id="z3" name="prover" value="z3">
              <label for="z3">Z3</label><br>
              <input type="radio" id="cvc4" name="prover" value="cvc4">
              <label for="cvc4">CVC4</label>
              <input type="submit" value="Prove">
              <script>
                /* $(document).ready(() => {runFrama();}); */
              </script>
            </form>


      <form action="" method="post" id="f{{ file.pk }}">
        {% csrf_token %}
      </form>
      <label for="f{{ file.pk }}">
        <div class="file" id="file{{ file.pk }}">{{ file.name }}</div>
      </label>
      <input type="submit" value="del" class="btn-sm" form="f{{ file.pk }}">
      <script>
      $(document).ready(() => {
        loadFile({{ file.pk }});
        deleteFile({{ file.pk }});
      });
      </script>


        </div>
        <div id="vcs" class="container tab-pane fade"><br>
        </div>
        <div id="result" class="container tab-pane fade"><br>
        </div>
      </div>

    </div>
  </main>

</div>
{% endblock content %}

cverifier/verifier/templates/verifier/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

cverifier/verifier/templates/verifier/tree_dir_template.html
<li class="directory" id="dir{{ dir.pk }}">
  <form action="" method="post" id="d{{ dir.pk }}">
    {% csrf_token %}
  </form>
  <label for="d{{ dir.pk }}">{{ dir.name }}</label>
  <input type="submit" value="del" class="btn-sm" form="d{{ dir.pk }}">
  <script>
  $(document).ready(() => {deleteDir({{ dir.pk }});});
  </script>
  <ul>
  {% for file in dir.file_set.all %}
    <li id="li{{ file.pk }}">
      <form action="" method="post" id="f{{ file.pk }}">
        {% csrf_token %}
      </form>
      <label for="f{{ file.pk }}">
        <div class="file" id="file{{ file.pk }}">{{ file.name }}</div>
      </label>
      <input type="submit" value="del" class="btn-sm" form="f{{ file.pk }}">
      <script>
      $(document).ready(() => {
        loadFile({{ file.pk }});
        deleteFile({{ file.pk }});
      });
      </script>
    </li>
  {% endfor %}
  </ul>
  <ul>
  {% for ch in dir.directory_set.all %}
    {% with dir=ch %}
      {% include 'verifier/tree_dir_template.html' %}
    {% endwith %}
  {% endfor %}
  </ul>
</li>